.all-contributorsrc
README.md

**What**: docs faq addition
**Why**: I read the faq, and even though the previous question addresses it I thought `queryByTestId` would handle this case, it doesn't so this faq addition clarifies the issue along with suggested ways to address it.
**How**:  N/A
**Checklist**:

(docs) Add faq entry about dealing with multiple data-testids

---

.all-contributorsrc
README.md
package.json
typings/index.d.ts

**What**: Added TypeScript definitions.
**Why**:  To let TypeScript's users better use library 😃.
**How**: Added definition file.
**Checklist**:

feat(typings): add ts definitions

---

README.md

Not sure if this should include a link to #11 from the README, and also a link from the `flushPromises` documentation section to this FAQ question (which I could not do anyway because you're not using markdown section titles for each question in the FAQ).

Add FAQ section about how flushPromises work (closes #11)

---

README.md
package.json
src/__tests__/__snapshots__/element-queries.js.snap
src/__tests__/__snapshots__/fetch.js.snap
src/__tests__/element-queries.js
src/__tests__/fetch.js
src/__tests__/forms.js
src/__tests__/mock.react-transition-group.js
src/__tests__/react-redux.js
src/__tests__/react-router.js
src/__tests__/shallow.react-transition-group.js
src/__tests__/stopwatch.js
src/__tests__/text-matchers.js
src/index.js
src/queries.js
typings/index.d.ts

**What**: Add the following methods
- queryByText
- getByText
- queryByPlaceholderText
- getByPlaceholderText
- queryByLabelText
- getByLabelText
**Why**: Closes #16 
These will really improve the usability of this module. These also align much better with the guiding principles :+1:
**How**:
- Created a `queries.js` file where we have all the logic for the queries and their associated getter functions
- Migrate tests where it makes sense
- Update docs considerably.
**Checklist**:

feat(render): add new query capabilities for improved tests

---

.all-contributorsrc
README.md

**What**: getByLabelText on readmy had `username-input` but should be `username`
**Why**: So docs are as accurate as they can be
**How**: readme pr
**Checklist**:

update readme for getByLabelText

---

README.md

as mentioned in #36 - documents usage for typescript user. 
could expand to its own thing in future if theres more typescript use cases required, but for now i just stuck it in the extend-expect section to limit the scope.

add documentation for using Matchers w/ Typescript

---

README.md

See https://twitter.com/kentcdodds/status/983828524514586626

Add note about snapshot diffing

---

.all-contributorsrc
.github/ISSUE_TEMPLATE.md
README.md

**What**:
- Documents GitHub flows for bugs and feature requests
- Recommends communities for asking questions instead of filing issues
**Why**:
https://twitter.com/samselikoff/status/991395669016436736
One difference I'm proposing is _not_ closing new feature requests to make it easier to use the GitHub UI to sort/filter/browse open requests. But closing issues and adding a "votes needed" is a valid idea, too.
**How**:
**Checklist**:

chore: document GitHub issues flow

---

.all-contributorsrc
README.md
examples/__tests__/update-props.js
src/__tests__/rerender.js
src/index.js
typings/index.d.ts

**What**:
Implement rerender callback in render result object.
**Why**:
As already discussed in https://github.com/kentcdodds/react-testing-library/issues/65
**How**:
Provide rerender callback in render result object. 
**Checklist**:

implement rerender

---

typings/index.d.ts

See https://github.com/kentcdodds/dom-testing-library/pull/29

fix: update getByTestId types

---

README.md

**What**:
**Why**:
**How**:
**Checklist**:

Copy in waitForElement docs

---

README.md

**What**: In the README's example instead of using `mockImplementationOnce` the code is now using `mockReturnValueOnce`.
**Why**: `mockReturnValueOnce` is shorter and easier to read making the example easier to follow.
**How**: N/A
**Checklist**:

Change mockImplementationOnce to mockResolvedValueOnce

---

src/__tests__/fetch.js

**What**: Uses `mockResolvedValueOnce` rather than `mockImplementationOnce`
**Why**: Inspired by #83 from @Gpx 
**How**: GitHub's editor :wink:
**Checklist**:

test: use mockResolvedValueOnce instead

---

README.md

**What**: Adding a paragraph recommending to use `fireEvent` over `Simulate`
**Why**:  ![spectrum](https://user-images.githubusercontent.com/767959/39768375-70724282-52e9-11e8-9619-2652626bb5ac.png)
**How**: N/A
**Checklist**:
I think it's worth updating the code examples as well, what do you think?
I also don't know how to put into words the "Dan Abramov told me so" part 😀

Add advice to use fireEvent over Simulate

---

.all-contributorsrc
README.md
package.json
src/__tests__/debug.js
src/index.js

**What**: add a debug convenience method
Also add @Gpx to contributors!
**Why**:
Closes #86
**How**:
- Just re-export everything from dom-testing-library to simplify maintainence
- Add a simple `debug` method to make it really easy to log the container.
**Checklist**:

feat(debug): add a debug convenience method

---

README.md
package.json
src/index.js
typings/index.d.ts

**What**:
Adds missing TypeScript definitions for the getAll* and queryAll* functions. Also adds type definition for re-exported `getQueriesForElement` function.
**Why**:
These additions more accurately reflect what the library does and they're helpful. I found that I could get rid of some calls to `querySelectorAll` in favor of `queryAllByTestId` in my tests, which was more convenient.
**How**:
Imported and reused the TS definitions from dom-testing-library to bind the get/query functions to the dom element.
**Checklist**:

fix(TS): Add missing getAll and queryAll functions to TS definitions

---

typings/index.d.ts

**What**:
Removes unused import to avoid naming conflict with export.
**Why**:
Prevents the following error when running tests for a TypeScript-based React app...
```
node_modules/react-testing-library/typings/index.d.ts
(8,3): Import declaration conflicts with local declaration of 'getQueriesForElement'.
```

Remove unused import to prevent naming conflict with export

---

README.md

**What**: Add info to readme about `React.Fragment` and its interaction with `container.firstChild`
**Why**: This is a gotcha many people might run into.
**Checklist**:
When rendering a component that has a `React.Fragment` as the root element.
`container.firstChild` will only grab the first child of the fragment, NOT the fragment JSX-tag

docs: add React.Fragment info

---

.all-contributorsrc
README.md
typings/index.d.ts

* exports `prettyDOM` from dom-testing-library in the
react-testing-library's typings file.
Fixes: #108
**What**:  adds an export for `prettyDOM` in react-testing-library's typing's file.
**Why**:  to prevent the Typescript compiler from erroring.
**How**:  an export line was added to the react-testing-library's typing's file.
**Checklist**:

fix: add missing prettyDOM export to typings file

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/Bug_Report.md
.github/ISSUE_TEMPLATE/Question.md
.github/PULL_REQUEST_TEMPLATE.md
.prettierrc
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
cleanup-after-each.js
examples/README.md
examples/__tests__/mock.react-transition-group.js
examples/__tests__/react-context.js
examples/__tests__/react-redux.js
examples/__tests__/react-router.js
examples/__tests__/shallow.react-transition-group.js
examples/__tests__/update-props.js
other/MAINTAINING.md
other/manual-releases.md
package.json
src/__tests__/debug.js
src/__tests__/end-to-end.js
src/__tests__/events.js
src/__tests__/fetch.js
src/__tests__/forms.js
src/__tests__/render.js
src/__tests__/rerender.js
src/__tests__/stopwatch.js
src/index.js
typings/index.d.ts

**What**: deprecate renderIntoDocument and make it the default
**Why**: Closes #116 
**How**:
- Code refactor
- My son is waiting for me... Otherwise I'd be more informative.
**Checklist**:
cc @hnordt @sompylasar

feat(render): deprecate renderIntoDocument and make it the default

---

README.md

**What**:
It fixes variable name in README.
**Why**:
Because great lib needs great docs!
**Checklist**:

Fixes variable name in readme

---

README.md

**What**:
Already renderIntoDocument is deprecated, i changed the readme

change renderIntoDocument to render on Readme

---

typings/index.d.ts

- export all types from 'dom-testing-library'
- use getQueriesForElement to get all GetsAndQueries
- remove duplicate code
**Why**: Prevents typings from breaking when 'dom-testing-library' is updated
**Checklist**:

clean up code from index.d.ts

---

typings/index.d.ts

**What**:
The `debug` function accepts an optional element as argument, and it was not declared.
**Why**:
Because without this users of this library that also use TypeScript will not be able to use `debug(element)`.
**How**:
By adding the corresponding argument in the type definitions.
**Checklist**:

fix(TS): declare optional argument to `debug`

---

typings/index.d.ts

**What**:
Add `baseElement` to `render` return type.
**Why**:
Because without it TypeScript code using this library won't be able to use `baseElement`, which is crucial to testing react portals, for example.
**How**:
By adding the `baseElement` property to the type definitions.
**Checklist**:

fix: Add baseElement to render return type

---

README.md

Related to https://github.com/kentcdodds/dom-testing-library/pull/82.
**What**: Use getByText instead of getElementByText in a code example, which seems like it was a typo.
**Why**: getElementByText is not exported by dom-testing-library as far as I'm aware, which could be confusing.
**Checklist**:

Replace getElementByText with getByText

---

typings/index.d.ts

**What**:
Update the typings to reflect that both arguments inside the render options are optional
**Why**:
Because TypeScript code using this library will not work when omitting one of the options.
**How**:
By updating the typings source file.
**Checklist**:

Update typings for optional option arguments

---

README.md

**What**:
**Why**:
**How**:
**Checklist**:

Docs: show CJS workaround for #169

---

README.md

**What**:
Well, I was struggling to mock the axios response following the main example here. After hours searching it, I've discovered that we can add the __mocks__ folder to mock functions.
**Why**:
I've added a small line of comment to reference about the manual-mocks to be more clear and facilitate to the beginners.
**How**:
I followed the example inside the [jest documentation](https://jestjs.io/docs/en/manual-mocks).
**Checklist**:
Kent, I'm new into the testing world and I didn't understand very well why in the doc example was created a __mocks__ folder just to mock the .get function. Why not only use the jest.mock('axios') instead? Thank you!

Reference about the mocks folder

---

README.md

**What**: I replaced the spy and MouseEvent bubbling in the README.md
**Why**: Handling clicks in this manner didn't work in my project, while `fireEvent.click(...)` did. Also a global search of this repo show the only instance of this handling occurring in the README.md
**How**:
**Checklist**:
- [ x] Documentation
- [ x] Tests
- [ x] Ready to be merged
If I'm wrong here, please tell me how. I'm new to open source and would like to learn. If I'm right, this one is such a gimme I feel I should earn a spot as a contributor with a separate task.
This library is awesome, keep up the great work!

removing use of spy to click an event in README.md

---

README.md

**What**:
The "clicks submit button" test was not working because it was missing
`handleClick`. Also, it did not have any expectation which is weird for
a test.
**Why**:
I think having the test more "real-worldly" will make it easier to understand.
**How**:
**Checklist**:

docs: ✏️ fix "handle submit" test and add expectation

---

README.md
package.json
src/__tests__/__snapshots__/render.js.snap
src/__tests__/render.js
src/index.js
typings/index.d.ts

**What**:
Adds the possibility to get a `DocumentFragment` version of the rendered component.
**Why**:
I have a test of a connected redux component, and I want to snapshot the diff between them after dispatching an action. Since `container` is a live binding, its `innerHTML` changes, meaning comparison becomes meaningless.
An extra advantage is IMO that you don't need to do `firstChild` on snapshots, as having the `Fragment` wrapper makes sense. At least in my mind 🙂 
**How**:
By upgrading `kcd-scripts` to a version with Jest 23, and adding a dependency on `JSDOM` which matches the one found in Jest (to not rely on dependency hoisting).
**Checklist**:

feat: add `asFragment` return value from `render`

---

package.json

**What**:
Remove unused dependency from `package.json`
**Why**:
This package is not used here directly. Dom-testing-library uses it though and declares it there already: https://github.com/kentcdodds/dom-testing-library/blob/master/package.json#L43
On the other hand, in case if dom-testing-library would use a new major version of the dependency, there will be unwanted package duplication, because this line will stay. 
Packages should not declare dependencies on other packages, that they actually do not use.
**Checklist**:
- (N/A) Documentation 
- (N/A) Tests 
- (N/A) Added myself to contributors table

Remove wait-for-expect from dependencies

---

README.md

**What**:
Adding an explanation on how to implement a `getByTestId` that looks for `data-test-id`.
**Why**:
Because people tend to ask this question.
**How**:
**Checklist**:

docs: ✏️ explain how to implement custo getByTestId

---

README.md

**What**:
**Why**:
**How**:
**Checklist**:

Docs: implement data-test-id query using helpers

---

README.md

This PR fixes the mistake in the custom renderer example as discussed on https://github.com/kentcdodds/react-testing-library/issues/204#issuecomment-433468647

fix typos in custom renderer example

---

README.md
src/__tests__/render.js
src/index.js

**What**: add (experimental) `flushEffects` API
**Why**: to prepare for hooks
The more that I've thought it over, the more I'm thinking it may actually be better to force people to flush effects intentionally (even if it is a little less ergonomic). In any case, I think it's not a bad thing to have.
**How**:
When `ReactDOM.render` is called, all in-flight effects are run synchronously (at least with the current implementation of hooks). If that ever changes, we can update the `flushEffects` implementation, but this allows people to test their hooks as they experiment with the new hooks API.
**Checklist**:

feat: add (experimental) flushEffects to prepare for hooks

---

.all-contributorsrc
README.md

**What**:
This fixes the samples mentioned in issue #225.
**Why**:
The code samples in the `README.md` were incorrect.
**How**:
I built my own custom renderer, and once I was happy that it was working, I backported the changes to the `README.md`.
**Checklist**:
Note that there are a few blank lines added to the `README.md`, a couple of which change the formatting (e.g. around the issue links in the data-testid section).  These were inserted by the repository's own  `pre-commit` hook (presumably running `prettier` or some such?).

Fix up custom render + rerender samples

---

README.md

**What**:
Update documentation to suggest using `configure()` instead of writing a custom render, when needing to override `data-testid`.
**Why**:
We've just added a handy `configure()` function to `dom-testing-library` to make it easier to do this, so we might as well point it out here instead of recommending the hard way.
**How**:
Updated `README.md`
**Checklist**:

docs: replace data-testid using configure rather than custom render

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/Bug_Report.md

**What**:
**Why**:
**How**:
**Checklist**:

add link to minimal repo for bug reproduction

---

typings/index.d.ts

**What**:
Add typings for new `hydrate` render option
**Why**:
Enables the new API to be used from TypeScript
**How**:
Pulled existing options into a new `RenderOptions` interface for clarity + reuse and added new member to that.
**Checklist**:
**Note**
The current TS definition of `container` has it as a _mandatory_ property (in the _optional_ options object).  This means that it's not possible to write `render(ui, { hydrate: true })`. Users would have to write `render(ui, { container: someNewContainerTheyveMade, hydrate: true })`.  This seems wrong.  Should `container` just be optional?

fix(TS): add hydrate typings

---

typings/index.d.ts

**What**: Bug
**Why**: The existing typescript definitions fail to compile with `--noImplicitAny` enabled. 
**How**: I forked the project and tested that the updated declaration compiles correctly.
**Checklist**:

Add explicit `any[]` annotation to Query definition

---

CONTRIBUTING.md
typings/index.d.ts

Continues pull request #290 
**What**:
Modifies typing declaration of testHook 
Also adds a section to remind contributors to check typings of API
**Checklist**:
- [N/A] Documentation
- [N/A] Tests
- [N/A] Added myself to contributors table

Fix typing of testHook

---

src/__tests__/test-hook.js
src/index.js
typings/index.d.ts

**What**: Added ability to access return value of custom hook call without requiring to use closures for it.
**Why**: https://github.com/kentcdodds/react-testing-library/issues/295#issuecomment-462800743
**How**: Using ref object approach similar to `useRef` hook
**Checklist**:
No tests were harmed by this change which actually surprised me a lot and my current mental capacity is unable to explain how is it possible 🤕 
Fixes #295

feat: testHook returns result ref object

---

examples/__tests__/react-context.js

**What**:
Fixed a plural typo
**Why**:
Less typos will look more neat and professional.
**Checklist**:
I fixed a critical typo issue

Fixed plural typo

---

.github/PULL_REQUEST_TEMPLATE.md
package.json
src/__tests__/old-act.js
src/act-compat.js
src/index.js

**What**: Add support for async `act`
**Why**: Closes #281
**How**: Unfortunately, we need to do a bit of attempts at polyfilling to ensure we support react-dom@16.8.0 for the foreseeable future. This means that we not only have to polyfill `act` itself, but also polyfill the async support of `act`. So I've done my best to detect whether `act` supports async. I feel pretty good about this solution. I'd rather this than detecting the version number anyway.
**Checklist**:

feat(act): Support async act 🎉

---

src/__tests__/act.js
src/act-compat.js
src/index.js

**What**:
**Why**:
**How**:
**Checklist**:
Closes #345 
Closes #347

findBy* for #345

---

README.md

I saw someone struggling to find the docs link in the Readme

Make docs links more prominent

---

src/__tests__/multi-base.js
src/__tests__/render.js
src/index.js

**What**:
Fix `baseElement` being overridden if no `container` was provided
**Why**:
I'm having a hard time grasping the difference between `baseElement` and `container` in the current implementation:
> The containing DOM node where your React Element is rendered in the container.
-- https://testing-library.com/docs/react-testing-library/api#baseelement-1
Considering the default values I imagined it as 
```html
<base-element>
<container>
<Component />
</container>
</base-element>
```
The `base-element` acts as a long living container that will hold every rendered container but can be isolated from the rest of the document.
What I'm basically trying to achieve is that the queries don't look inside document.body but rather only in the DOM tree rendered by the component. It's not so much …

fix: Specify baseElement without container

---

typings/index.d.ts

**What**: Delete duplicate `Query` and `Queries` declarations and reuse them from `@testing-library/dom` instead.
**Why**: I mistakenly exported `Queries` interface when I shouldn't have in PR #396 - it was already being exported by `@testing-library/dom`. Also see https://github.com/testing-library/react-testing-library/pull/331#pullrequestreview-217309669. Apologies for the original PR!
**How**: Deleted duplicate declarations and tested locally against the latest versions of RTL/DTL.
**Checklist**:

fix(TS): use `Queries` from @testing-library/dom

---

src/__tests__/new-act.js
src/__tests__/old-act.js
src/act-compat.js

The previous version of async act detection left an open hanging act scope, which broke tests and expectations. This PR delays the detection until it's been called at least once.
I tested this with 16.8.6, and 0.0.0-b4178af81.

fix(act): async act detection

---

src/act-compat.js

**What**:
fix #414 
**How**:
use import instead require
**Checklist**:

Don't mix require and import

---

README.md

**What**: This PR documents the issue discussed in https://github.com/testing-library/react-testing-library/issues/281 and how to circumvent it
**Why**: As of right now, React DOM 16.9 has not been released. Thus, it can be useful to have a notice about the warnings in the README. We may remove these changes some weeks after React 16.9 is released.
**Checklist**:

docs: Document known issue with React 16.8

---

cleanup-after-each.js
src/__tests__/cleanup-after-each.js
src/act-compat.js
src/cleanup-async.js

**What**:
This PR adds an async `act()` call to `cleanup-after-each`. 
**Why**:
Tests, especially those with async logic, could have hanging microtasks or React work that could leak into the next test. 
**How**:
This PR
- adds `cleanup-after-each.js` (so I can write tests for it)
- awaits an `act(async () => {})` call before unmounting containers
- And a test for the same
**Some possible Q&A**:
- Why not do a sync `act()` in `cleanup()`?: If peeps are using react-testing-library, it's suuuper unlikely they'll have hanging sync effects/updates. Decided not to add code without a good reason.
(bonus: fixes a lint violation in act-compat.js)
**Checklist**:

await act(...) inside cleanup-after-each

---

package.json
src/__tests__/old-act.js
src/act-compat.js
src/react-dom-16.9.0-is-released.js

**What**:
improve warning so people know they can upgrade to 16.9.0 now
**Why**:
Closes #281
**How**:
Removed the `src/react-dom-16.9.0-is-released.js` because it's released now! Update the tests to not mock that module because it's no longer needed.
**Checklist**:

fix: improve warning so people know they can upgrade to 16.9.0 now

---

package.json
pure.js
src/__tests__/auto-cleanup-skip.js
src/__tests__/auto-cleanup.js
src/index.js
src/pure.js
tests/setup-env.js

**What**:
automatically call `cleanup` (with async act) if `afterEach` is detected.
**Why**:
Closes #428
This effectively means that 90% of users wont even have to know about `cleanup` at all. Which is a huge improvement.
**How**:
You can disable this with the `RTL_SKIP_CLEANUP` environment variable if you so choose, but it's recommended to have cleanup work this way.
**Checklist**:
[docs site](https://github.com/alexkrolick/testing-library-docs) Let's get this reviewed/merged first, then we can start working on the docs.

feat(cleanup): automatically cleanup if afterEach is detected

---

dont-cleanup-after-each.js
package.json

**What**: add dont-cleanup-after-each.js
**Why**:
This makes it easier for folks who don't want to write their tests in an isolated way. It's totally not recommended, but it will hopefully reduce pain while people migrate from one testing style to another.
**How**:
This is just a simple file that sets the RTL_SKIP_AUTO_CLEANUP environment variable so that RTL doesn't setup automatic cleanup. 
**Checklist**:
[docs site](https://github.com/alexkrolick/testing-library-docs) [done](https://github.com/testing-library/testing-library-docs/pull/215)
I decided to do this after reading https://github.com/testing-library/react-testing-library/pull/430#issuecomment-520142114

feat: add dont-cleanup-after-each.js

---

package.json
typings/index.d.ts

**What**:
Closes #436 by putting maintenance burden for `act` types on `@types/react-dom`. async `act` will be supported once https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37554 is merged.
**Why**:
If act is exported from `react-dom/test-utils` we export it as well. The types should reflect that.
**How**:
Conditional types
**Checklist**:
- ~[ ] Documentation added to the
[docs site](https://github.com/alexkrolick/testing-library-docs)~

fix: Act type

---

src/__tests__/old-act.js
src/act-compat.js

**What**: This is a bug fix to ensure proxied `console.error` calls are passed through correctly.
**Why**: Without them, `console.log('Value:', 1)` would get logged as `['Value:', 1]` instead of `Value: 1`.
**How**: I'm not sure how this applies.
**Checklist**:

fix: spread console error args when proxying

---

src/__tests__/rerender.js

**What**:
This PR fixes issue: #464 by writing the test slightly different so no if statement is needed anymore
**Why**:
Validation step is currently failing because of the eslint rule: jest/no-if.
**How**:
Not doing a querySelector and checking if it found the initial input element anymore, but actually creating these elements so no queryselector is needed anymore
**Checklist**:
[docs site](https://github.com/alexkrolick/testing-library-docs)~~

fix: eslint jest/no-if in rerender test

---

README.md

**What**:
referenced incorrect state variable
state.success --> state.resolved
**Why**:
Complex example is broken.
**How**:
**Checklist**:

incorrect referenced variable

---

src/__tests__/old-act.js
src/act-compat.js

What:
This PR fixes issue: #442 by adding type checking for args used in asyncAct function.
Why:
Current implementation assumes console.erorr was always called with a string even though it could be called with other types.
How:
Wrapped execution of code in a type check if statement to ensure operations are done only on string types.
Checklist:

fix: console.error doesn't have to be a string in act.compat.js

---

package.json

**What**: Adds a "pure" build for bundling with rollup (and parallelizes all build scripts)
**Why**: Closes #486
**How**: Used the environment variables supported by the kcd-scripts rollup config: https://github.com/kentcdodds/kcd-scripts/blob/bd3c762c0202ac3564bb6a329e3e9e972795b5e7/src/config/rollup.config.js so we can make the pure.js file an entry and set the output filename suffix (so it doesn't overwrite the existing build).
**Checklist**:
[docs site](https://github.com/alexkrolick/testing-library-docs) N/A. I don't think the UMD is something we really document or need to honestly.

feat: add pure bundle build

---

src/__tests__/debug.js
src/pure.js

**What**: 
Adds the ability to log an array of containers.
**Why**:
Right now, if you try to debug the output of a queryAll or getAll, you will receive an error. This will allow everyone to see the output of each container inside of the output of that query.
**How**:
Checks if the received container is an array, if so, logs each element of it.
**Checklist**:

feat(debug): allow debugging an array of containers

---

.travis.yml

**What**: Test react's `next` versions
**Why**: https://reactjs.org/blog/2019/10/22/react-release-channels.html#using-the-next-channel-for-integration-testing
**How**: added a step to the install in our `.travis.yml` which will upgrade react and react-dom to the `next` release if we're running the cron job.
**Checklist**:

chore(ci): add cron job install script for smoke testing next

---

src/flush-microtasks.js
src/index.js

This is the rebase of #440. I've squashed both commits into the original commit.
Original description:
> This PR replaces calling async act() in afterEach, with a version that still flushes microtasks, but doesn't wrap with act().
> 
> Explanation: If there are any hanging microtasks, that means a test ran without asserting on a valid state. Any async portion that causes updates should be asserted on, or atleast resolved within the scope of a test. This PR should still fire missing act warnings for a test, but won't let it leak to the next one.
>

manually flush microtasks in afterEach

---

src/flush-microtasks.js

**What**:
Closes #521 
**Why**:
Warning was a false positive
**How**:
Correctly translate 
```js
warningWithoutStack(
typeof MessageChannel !== 'undefined',
'This browser does not have a MessageChannel implementation, ' +
'so enqueuing tasks via await act(async () => ...) will fail. ' +
'Please file an issue at https://github.com/facebook/react/issues ' +
'if you encounter this warning.',
);
```
`warningWithoutStack` (like [`warning`](https://www.npmjs.com/package/warning)) works different than `console.error` and is very confusing (which is also why react is getting rid of it)
**Checklist**:
check an item, place an "x" in the box like so: "- [x] Documentation" -->
- ~[ ]~ Typescript …

fix: False positive warning about MessageChannel

---

.codesandbox/ci.json

**What**:
Build package in PRs for codesandbox
Closes #533
**Why**:
Integration testing, shareable live playground of new features etc
**How**:
https://twitter.com/codesandbox/status/1181184975460282368
**Checklist**:
- ~[ ] Documentation added to the
[docs site](https://github.com/alexkrolick/testing-library-docs)~
- ~[ ] Tests~
- ~[ ] Typescript definitions updated~

test: Build in CodeSandbox CI

---

index.d.ts

When installed with pnpm, the `@types/testing-library__react` package cannot be used by packages that don't directly depend on it, so we need to re-export them.

fix: support automatic types in pnpm installs

---

README.md

Fixed example code to use `screen`.

docs: Fixed example code to use "screen"

---

README.md

**What**: Fixing an error on readme
**Why**: In the complex example catch already sets error to ```error.message```. So in render, it should just show ```state.error```.
**How**: Render function updated to just show ```state.error``` instead of ```state.error.message```.
**Checklist**:
Yes. Either that or catch shoud update error on the state as ```error: error``` instead of ```error: error.message```

Fix error on complex example

---

src/__tests__/events.js
src/pure.js

(#577)
**What**:
Make `fireEvent.mouseEnter` and `fireEvent.mouseLeave` work with events added using `addEventListener`.
**Why**:
There is no way to trigger a native mouseEnter/mouseLeave event using React Testing Library. A workaround is to manually use `dispatchEvent`, but it's not as convenient as `fireEvent`. The reason for this limitation is due to how React handles mouseEnter/mouseLeave: https://github.com/facebook/react/issues/12978
**How**:
Instead of setting `fireEvent.mouseEnter/Leave` to `fireEvent.mouseOver/Out`, set `fireEvent.mouseEnter/Leave` to call both `mouseEnter/Leave` and `fireEvent.mouseOver/Out`. 
This makes the behavior match other events that can be called with `fireEvent`. For example, if one click handler was added to an element with `addEventListener` and …

fix: make fireEvent mouseEnter/mouseLeave work with addEventListener

---

README.md

**What**:
Update `@testing-library/jest-dom` import statement to latest syntax in the README example.
**Why**:
[@testing-library/jest-dom v5.0.0](https://github.com/testing-library/jest-dom/releases/tag/v5.0.0) later, import statement had BreakingChange.
**How**:
Edit README.md
`import '@testing-library/jest-dom/extend-expect'` to `import '@testing-library/jest-dom'`
**Checklist**:
Thank you for you made useful library &  maintaining actively! 😀

README: update @testing-library/jest-dom's old syntax

---

src/__tests__/debug.js
src/pure.js

**What**: make debug accept the same args as prettyDOM
**Why**: Closes #580 
**How**: Accepting additional args and forwarding them along.
**Checklist**:

feat(debug): accept the same arguments as prettyDOM

---

.travis.yml
package.json

**What**:
Updating the engine to Node v.10.
**Why**:
Node v.8 no longer has LTS. Closes https://github.com/testing-library/react-testing-library/issues/575
**How**:
Updating the engine field in `package.json` & `.travis.yml` respectively.
**Checklist**:
- [N/A] Documentation added to the
- [N/A] Tests
- [N/A] Typescript definitions updated

Drop Node 8 support

---

src/__tests__/cleanup.js
src/index.js
src/pure.js

BREAKING:
`cleanup` is now async.
```diff
- cleanup();
+ await cleanup();
```
**What**:
Flushes microtasks (introduced in #514) in cleanup instead of afterEach
**Why**:
Flushing microtask is not available for users of the `/pure` build.
**How**:
Move logic from index#afterEach into pure#cleanup
**Checklist**:

feat: Flush microtasks in cleanup

---

cleanup-after-each.js
package.json

It was deprecated in the last release, so we could safely delete it now I think 🙂

Remove cleanup-after-each

---

package.json

**What**:
Closes #616
**Why**:
Propagates downstream fix faster.
**How**:
Bump minimal required version from 7.0.2 to 7.0.3
**Checklist**:
- ~[ ]~ Tests

fix: bump minimal /dom version

---

package.json

**What**:
Bump @types/testing-library__react to ^10.0.0
**Why**:
I can't use new stuff from v10 because types are outdated
**How**:
Increased number in package.json
**Checklist**:

fix: Bump types dependency

---

src/act-compat.js

There is a small typo in src/act-compat.js.
Should read `seamless` rather than `seemless`.

docs: Fix simple typo, seemless -> seamless

---

src/flush-microtasks.js

**What**:
closes #614
**Checklist**:

fix: restore this when requiring timers

---

README.md

**What**: Added about the yarn installation process.
**Why**: For developers who run the build using yarn 
**How**: Adding the yarn add bash command.
**Checklist**:

docs(readme): Add install command for yarn

---

.travis.yml
src/fire-event.js
src/pure.js

**What**: fix(fireEvent): automatically configure `fireEvent` to be wrapped in act 
**Why**: Because now we don't have to do this nonsense: https://github.com/testing-library/react-testing-library/blob/0afcbea3c3d1ddce218a36d963d39fa83f9a7cf6/src/pure.js#L107-L128
It also means that `fireEvent` will be globally configured to be wrapped in `act` so even if people import the DOM Testing Library one (like we do in `@testing-libary/user-event`), it will be wrapped in act (assuming they've also imported `@testing-library/react`).
One note is that `pure.js` is not actually pure and never was because it configures DOM Testing Library globally. Perhaps in the future we should make a breaking change to make `pure.js` actually pure.
**How**:
**Checklist**:
Now not only will React Testing Library's …

fix(fireEvent): automatically configure `fireEvent` to be wrapped in act

---

index.d.ts
package.json
types/index.d.ts
types/pure.d.ts
types/test.tsx
types/tsconfig.json
types/tslint.json

**What**:
Improve support of typings by bringing them into this repo instead of relying on a versioned external repo
**Why**:
Help with stability for consumers using typings and give a clearer understanding of what should be supported in a given version without having to reference multiple repos.
**How**:
Modeled after these changes in a sibling repo: https://github.com/testing-library/dom-testing-library/pull/530
**Checklist**:
Currently this does not validate with several errors for Typescript@4.0, example:
```
ERROR: 6:23   expect      TypeScript@4.0 compile error:
Cannot use JSX unless the '--jsx' flag is provided.
```
I'm still investigating this, but if anyone knows more about `dtslint` I'm all 👂

[WIP] Bring typings from DefinitelyTyped into this repo

---

src/index.js

**What**:
`cleanup()` now runs not only when `afterEach()` exists. It also runs when `teardown()` exists.
**Why**:
There are test runners that either don't have a `afterEach()` function or supports different UI's, like [Mocha's TDD UI](https://mochajs.org/#tdd) for example. It would be great if `react-testing-library` would also support `teardown()` for cleaning up things.
**How**:
I just added an additional check that checks and calls `teardown()` instead of `beforeEach()`.
**Checklist**:
The main problem that I have with this pull request is:
- linting fails because `teardown` is not defined. Is this somewhere deep in `eslint-config-kentcdodds`?
- I had problems to write a test for that because you are using `Jest` which …

Run cleanup() when test runner supports teardown()

---

README.md

**What**:
Uses `msw` library for API mocking in the test suite example in README.
**Why**:
These changes are implemented similar to the [React Example](https://testing-library.com/docs/react-testing-library/example-intro) from the Testing Library documentation. 
**How**:
- Initial request handler via `setupServer`
- Per-test setup handler via `server.use()`, allowing to test an error scenario
**Checklist**:
- Follow up to https://github.com/testing-library/testing-library-docs/issues/482

docs: use "msw" for API mocking in examples

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/Bug_Report.md
.github/ISSUE_TEMPLATE/Question.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

**What**:
Clean up of links and re-add section on Updating Typings now that they are within this project.
**Why**:
Follow up on #690 
**Checklist**:

[Chore][Docs] Update links and re-add typings section

---

README.md

**What**:
You need to add window.localStorage.removeItem('token') to afterEach() within '__tests__/login.js' file in Complex Example in README.md file.
**Why**:
The token value exists in localstorage due to the first test suite. This causes the second test suite to fail.
**How**:
Adding window.localStorage.removeItem('token') code to the afterEach() callback function argument solved the problem.
**Checklist**:

docs: Add window.localStorage.remove('token') statement to afterEach() in tests/login.js file

---

src/flush-microtasks.js

**What**: microtask flushing now supports fake timers
**Why**: So people can use fake timers in their react tests without it causing issues with React's scheduler
**How**:
- Three days of total pain and anguish...
- Detect whether we're using fake timers and if we are, advance them forward.
**Checklist**:
~- [ ] Documentation added to the [docs site](https://github.com/testing-library/testing-library-docs)~ N/A
~- [ ] Tests~ N/A (really really hard to reproduce)
~- [ ] Typescript definitions updated~ N/A

fix(cleanup): microtask flushing now supports fake timers

---

src/__tests__/cleanup.js
src/pure.js

**What**:
The `cleanup` routine should unmount mounted containers first to trigger all the effect cleanup routines and _then_ flush the microtask queue.
**Why**:
When using some libraries such as `react-query` or `react-modal`, there can be unmounting routines that schedule immediate microtasks to perform cleanup.
I've documented a specific case [here in react-query](https://github.com/tannerlinsley/react-query/issues/270#issuecomment-610560262) where I was seeing testing inconsistencies unless I explicitly called `unmount` during the test.
In React Modal specifically, here's a snippet from one of their `componentWillUnmount` cleanup routines:
https://github.com/reactjs/react-modal/blob/v3.11.2/src/components/Modal.js#L153-L172
**How**:
I moved the `await flush()` to be after unmounting …

fix(cleanup): Cleanup should flush microtask queue after unmounting containers

---

.travis.yml

**What**:
- Tests with both React stable and next for all builds (push and cron)
- Allow next releases to fail the build so we can still release
- Solves cron issues like #726 that are only caused by next releases
**Why**: #726 and greater visibility of what's failing in React next (before a cron build is started on schedule)
**How**: Split React next into a new section of the build matrix rather than just using it in cron builds
**Checklist**:

chore: create new jobs for React next

---

src/flush-microtasks.js

Closes #736 
**What**: When we couldn't require the `scheduler` package we will now fallback to `isModernScheduleCallbackSupported = false` meaning we will use `callback => callback()`. 
**Why**: Following the conversation in #736 - We found this to be a proper solution for now in case the `Scheduler` wasn't loaded.
I still think we need to discuss this issue further and think if we can be able to figure a different way to require the `Scheduler` at runtime.
**How**: I've added an if statement in the catch block to see if `isModernScheduleCallbackSupported` is `true`, in that case I change it to `false` and write an error to console.
I think that we may need to separate the try catch to two different ones and handle each error for it's own. Update me what you think please :)
Also, within …

fix(flushMicroTasks): Fallback to no scheduler in case of exception

---

package.json
src/__tests__/cleanup.js
src/flush-microtasks.js

**What**: This removes the scheduler code from flush-microtasks
**Why**: Because the test that failed is fundamentally flawed
**How**:
1. Rewrite the test to illustrate why it's flawed (we can't and shouldn't guarantee that all scheduled tasks will run simply as a result of cleanup)
2. Rewrite the test to not test for that
3. Fix the implementation of flush-microtasks to not use the scheduler (basically revert everything we did for #726 and change the test instead).
**Checklist**:
~- [ ] Documentation added to the [docs site](https://github.com/testing-library/testing-library-docs)~ N/A
~- [ ] Typescript definitions updated~ N/A
Closes #743

fix(cleanup): remove scheduler code from flush-microtasks

---

src/__tests__/render.js
src/pure.js

**What**:
Flush cleanup functions from `useEffect` synchronously on `unmount`.
**Why**:
`react@next` no longer flushes cleanup functions from `useEffect` synchronously.
Verified in https://travis-ci.org/github/testing-library/react-testing-library/builds/708314737
**How**:
Wrap `unmountComponentAtNode` in `act`.
**Checklist**:
I'm not touching `cleanup` and `flush-microtasks` for now. We can do that in a follow-up PR that we test extensively against existing repos.

fix(unmount): Flush useEffect cleanup functions syncronously

---

src/__tests__/events.js

**What**:
Add expected behavior for blur and focus bubbling in React. This is different than native DOM events where blur and focus do not bubble
**Why**:
Got messaged by core members that they **might** start listening to `focusin`/`focusout` instead which would cause our current `fireEvent.focus` implementation to not register React focus events. We should also fire `focusin`/`focusout` once they start doing that (i.e. `react@next` starts breaking the build) which is similar to [how we handle `mouseEnter`/`mouseLeave`](https://github.com/testing-library/react-testing-library/blob/6147830b0ea61341d02f520d2a26b817996e3a4a/src/fire-event.js#L13-L25).
Ideally we'd get everybody on board to using `.focus()` and `blur()` instead but that would only work with `jsdom@16.3.0` or a browser which …

test(fireEvent): Add expected behavior for blur/focus in React

---

package.json

**What**:
Bumping @testing-library/dom to 7.22.3. 
**Why**:
When running tests in my project, I am seeing this `console.error` happen:
```
console.error
Error: Not implemented: window.computedStyle(elt, pseudoElt)
at module.exports (/Users/ryan/code/covidence/covidence/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
at Window.getComputedStyle (/Users/ryan/code/covidence/covidence/node_modules/jsdom/lib/jsdom/browser/Window.js:657:7)
at computeMiscTextAlternative (/Users/ryan/code/covidence/covidence/node_modules/dom-accessibility-api/sources/accessible-name.ts:347:24)
at computeTextAlternative (/Users/ryan/code/covidence/covidence/node_modules/dom-accessibility-api/sources/accessible-name.ts:576:11)
at computeAccessibleName …
```

fix: Bump @testing-library/dom to 7.22.3

---

README.md

**What**:
Improve some documentation in Readme.md
**Why**:
**How**:
**Checklist**:

docs: Improve some documentation

---

types/index.d.ts

**What**:
Update types for cleanup function. `cleanup` became sync, but in typings it returns Promise.
Update was there: https://github.com/testing-library/react-testing-library/pull/768
**Why**:
Cause now types are not valid for real code.
**How**:
Just manually update typings)
**Checklist**:
It might be cool to update typings automatically. I can create an issue, but do not have much time to implement it(

fix: Update typings for cleanup

---

src/index.js

**What**:
removed async/await on cleanup afterEach
**Why**:
no longer needed due to 11.0
**Checklist**:

fix(cleanup): remove unnecessary async/await

---

src/__tests__/events.js
src/fire-event.js

**Pointer events added**:
**Existing code doesn't include pointer events**:
**Similar to the mouse events**:
**Checklist**:

fix: Trigger onPointerEnter/Leave when calling pointerEnter/Leave

---

package.json
src/__tests__/events.js

**What**:
Calling `fireEvent.gotPointerCapture` or `fireEvent.lostPointerCapture` should trigger their corresponding React event listeners.
**Why**:
Reveals issues with `gotpointercapture` and `lostpointerapture`
**How**:
- add all [pointer event types](https://www.w3.org/TR/pointerevents/#pointer-event-types) to our existing test suite
**Checklist**:
- ~[ ] Documentation added to the
[docs site](https://github.com/testing-library/testing-library-docs)~
- ~[ ] Typescript definitions updated~

fix: Trigger ongot-/onlostpointercapture when calling got-/lostpointercapture

---

README.md

**What**: 
I update README.md complex example section. So, the test will be valid.
**Why**:
1) There was missing variable. 
2) I have seen that the promise always succeeds, so the tests always fail. The Promise returned from fetch() won’t reject on HTTP error status even if the response is an HTTP 404 or 500([reference](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)).
**How**:
I added the missing variable and fixed the promise to reject in case of `200<` status code.
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) - N/A

docs: update complex example

---

.travis.yml

**What**:
Explicitly add node 15 to the matrix and fix compat issues.
**Why**:
We declare that we support node >= 10 so we should test accordingly. Now that node 15 is released we can declare it in the matrix.
**How**:
Follow advise in https://github.com/npm/cli/issues/1935 until npm fixes its CI detection.
**Checklist**:

test: Fix node 15

---

README.md
src/__tests__/act.js
src/__tests__/auto-cleanup-skip.js
src/__tests__/auto-cleanup.js
src/__tests__/cleanup.js
src/__tests__/debug.js
src/__tests__/end-to-end.js
src/__tests__/events.js
src/__tests__/multi-base.js
src/__tests__/render.js
src/__tests__/rerender.js
src/__tests__/stopwatch.js
src/act-compat.js
src/pure.js

https://twitter.com/kentcdodds/status/1321885232878923776

chore: update React imports

---

package.json

**What**:
I have updated a bunch of dependencies including the @testing-library/dom dependency
**Why**:
Mainly to get the new shiny new speed fix in @testing-library/dom into this the React library
**How**:
Updated package.json
**Checklist**:

chore: upgrade dependencies, typescript, @testing-library/dom etc

---

package.json
types/index.d.ts

**What**: fix #694
**Why**: Because it causes type error
**How**: Importing the module from `@testing-library/dom`
**Checklist**:

fix: import pretty-format from @testing-library/dom

---

types/test.tsx

**What**: Adding regression tests for #830 (implemented in #833)
**Why**: It helps to have a regression test for the original issue when adding a fix
**How**: TypeScript type test based on sample code in #830
**Checklist**:

chore(types): add test for rendering SVG elements

---

package.json

**What**: bump dom testing lib to latest
**Why**: to fix a bug found in suggestions.
**How**: yarn install
**Checklist**:

fix(dependencies): bump dom testing library

---

package.json
src/__tests__/rerender.js
types/test.tsx
types/tsconfig.json
types/tslint.json

**What**: Update all deps
**Why**: Just to get things up-to-date.
**How**: `npx ncu --dep prod,dev --upgrade && npm run lint -- --fix && npm run validate`
**Checklist**:
Any maintainer is welcome to merge this 👍

chore: update all deps

---

types/index.d.ts

https://github.com/testing-library/react-testing-library/issues/856
**Checklist**:

fix: Return type of unmount is `void`

---

types/index.d.ts
types/test.tsx

**What**:
Fixes https://github.com/testing-library/react-testing-library/pull/834#issuecomment-767796456
**Why**:
By default we create a `div` but declare that the type is `Element`. This is not specific enough for most use cases since e.g. `offsetHeight` isn't implemented in `Element`
**How**:
Adding a type parameter as anticipated in https://github.com/testing-library/react-testing-library/pull/833#issuecomment-730280641
**Checklist**:

fix(render): Default to HTMLElement in returned container

---

types/index.d.ts
types/test.tsx

**What**:
Fixed type definition
**Why**:
`v11.2.3`
```tsx
import { render, fireEvent } from '@testing-library/react'
const { getByText } = render(<div />, options)
fireEvent.click(getByText('foobaz')) // no type error
```
`v11.2.4`
```tsx
import { render, fireEvent } from '@testing-library/react'
const { getByText } = render(<div />, options)
fireEvent.click(getByText('foobaz')) // TS2345: Argument of type 'Error | HTMLElement | HTMLElement[] | Promise<HTMLElement[]> | Promise<HTMLElement> | null' is not assignable to parameter of type 'Element | Node | Window | Document'.
```
`v11.2.4-fixed`
```tsx
import { render, queries, fireEvent } from '@testing-library/react'
const { getByText } = render<typeof queries>(<div />, options)
fireEvent.click(getByText('foobaz')) //  no type error
``` …

fix(render): add default type for Queries parameter

---

src/index.js

Hi all 👋
**What**:
Fixes
```
ReferenceError: process is not defined
at eval (webpack-internal:///./node_modules/@testing-library/react/dist/@testing-library/react.esm.js:458:1)
```
when @testing-library/react is being used with webpack 5 and karma.
**Why**:
Webpack 5 doesn't shim Node's `process` object by default anymore. Only instances of `process.env.NODE_ENV` are replaced statically. This means that unguarded checks of `process.env` will crash in browser environments.
**How**:
I was wondering if there should also be a check in `dont-cleanup-after-each.js`. I decided against it since this would need to define a global `process` object in order to define the env variable. After all, it's the app developer's responsibility to provide a global `process` object in this case.
**Checklist**: …

fix: Guard against `process` not being defined

---

package.json

BREAKING CHANGE: Bumps `@testing-library/dom` to 8.0.0-alpha.3.
For a comprehensive list of breaking changes see the individual releases:
- https://github.com/testing-library/dom-testing-library/releases/tag/v8.0.0-alpha.1
- https://github.com/testing-library/dom-testing-library/releases/tag/v8.0.0-alpha.2
- https://github.com/testing-library/dom-testing-library/releases/tag/v8.0.0-alpha.3
**What**:
**Why**:
To propagate all the fixes/features from `@testing-library/dom`
**How**:
Bump `@testing-library/dom` to 8.0.0-alpha.3. The stable release of /react@12.x will use the stable release of /dom@8.x
**Checklist**:
- ~[ ]~ Tests

fix: Bump testing-library/dom to v8 alpha

---

package.json
src/__tests__/cleanup.js
src/__tests__/debug.js
src/__tests__/new-act.js
src/__tests__/no-act.js
src/__tests__/old-act.js
src/__tests__/render.js
types/test.tsx

Targetting `alpha` since `@testing-library/dom@latest` is not compatible with jest 27
**What**:
Update `npm run validate` dependencies
**Why**:
To stay up-to-date with latest dependencies
**How**:
Bump `kcd-scripts` incrementally up until 11.x. Each commits bumps by a major so review by commit is advised.
**Checklist**:

chore: Bump kcd-scripts to 11.x

---

src/__tests__/cleanup.js
src/__tests__/no-act.js
src/__tests__/stopwatch.js
tests/setup-env.js

**What**:
Fix test failures on `next` and `experimental` jobs
**Why**:
The tests are failing in a way that isn't actionable for us at the moment
**How**:
Ignore `ReactDOM.render` and `ReactDOM.hydrate` deprecation warnings 
**Checklist**:

test: Ignore React 18 legacy root deprecation warnings

---

.codesandbox/ci.json
.github/workflows/validate.yml
package.json

BREAKING CHANGE: node 10 is no longer supported. It reached its end-of-life on 30.04.2021.
**What**:
Closes https://github.com/testing-library/react-testing-library/issues/913
Closes https://github.com/testing-library/react-testing-library/pull/927
**Why**:
Reduces maintenance burden
**How**:
Change `engines` field to require `node>=12`
**Checklist**:
Will do once we release the alpha

feat: Drop support for node 10

---

package.json

Closes https://github.com/testing-library/react-testing-library/issues/918
BREAKING CHANGE: Remove `waitForElement`. `<style />`, `<script />` and comment nodes are now ignored by default in `pretty-dom`.
**What**:
- Remove `waitForElement` https://github.com/testing-library/dom-testing-library/pull/969
- Add `filterNode` to `pretty-dom` https://github.com/testing-library/dom-testing-library/pull/907
**Why**:
Propagate changes in /dom to /react users
**How**:
Bump `@testing-library/dom` to latest `alpha`
**Checklist**:

fix: Update @testing-library/dom

---

.codesandbox/ci.json
.github/workflows/validate.yml
package.json
src/__tests__/cleanup.js
src/__tests__/debug.js
src/__tests__/new-act.js
src/__tests__/no-act.js
src/__tests__/old-act.js
src/__tests__/render.js
src/__tests__/stopwatch.js
tests/setup-env.js
types/test.tsx

BREAKING CHANGE: Bump `@testing-library/dom` to 8.0.0. Please check out the [`@testing-library/dom@8.0.0` release page](https://github.com/testing-library/dom-testing-library/releases/tag/v8.0.0) for a detailed list of breaking changes.
BREAKING CHANGE: node 10 is no longer supported. It reached its end-of-life on 30.04.2021.
**What**:
Propagate fixes and features from latest `@testing-library/dom` major
**Why**:
- up to date with latest fixes/features
- especially clock related changes are important to debug concurrent react testing better and ensure compat with jest 27
**How**:
Bump `@testing-library/dom` to latest
**Checklist**:

chore: Release v12 as stable

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

**What**:
Update links (e.g. egghead.io link redirects to some old preview page for their newly launched site).
Renamed `Typescript` to `TypeScript`
(As I did with my first PR on the cypress-testing-library (https://github.com/testing-library/cypress-testing-library/pull/180))
**Why**:
It could be confusing for first-time contributors (egghead.io links)
It gives a even more professional look when the naming of tools etc. is spelled correctly (at least to me 😅)
**How**:
Searched for the correct links:
OLD: https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github
NEW: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
Have found a source to link why I would like to update the TypeScript spelling: …

docs(CONTRIBUTING): update links

---

src/__tests__/end-to-end.js

**What**:
Adds tests for `waitFor`, `waitForElementToBeRemoved` and `findBy` across all supported timer implementations (real timers, jest legacy fake timers, jest modern fake timers).
**Why**:
These offer a more granular coverage that's required for https://github.com/testing-library/react-testing-library/pull/937. 
The new tests are also the only tests that would trigger a missing act warning if we were to remove the `asyncWrapper`.
**How**:
Backport tests from https://github.com/testing-library/react-testing-library/pull/937 and convert the class component to a function component. With a class component we'd still not get a missing act warning.
**Checklist**:
- ~[ ]~ TypeScript …

test: Backport tests using the full timer matrix

---

types/index.d.ts
types/test.tsx

**What**: This adds an option for the wrapper to use a simple function component
**Why**: Closes #965
**How**: Added the option to the types for `render`
**Checklist**:

fix(TS): make wrapper allow a simple function comp

---

types/index.d.ts
types/test.tsx

**What**:
Closes https://github.com/testing-library/react-testing-library/issues/970
Closes https://github.com/testing-library/react-testing-library/issues/972
**Why**:
Broke in https://github.com/testing-library/react-testing-library/pull/966
**How**:
Implicit children strikes yet again. While `FunctionComponent` adds implicit children, its `propTypes` do not so we didn't catch that issue. We don't care about React statics and just that we can pass it to `createElement` (or any JSX runtime). 
**Checklist**:

fix(render): Don't reject wrapper types based on statics

---

jest.config.js
src/__tests__/render.js
src/pure.js

**What**:
Fix "missing act" warnings when calling `render(ui, {container, hydrate})` using `react@alpha`.
**Why**:
Previous `hydrateRoot` usage was just wrong (see https://github.com/facebook/react/issues/22643 for more information).
**How**:
Call `hydrateRoot` with the given `ui` and wrapped in `act`
**Checklist**:

fix(render): Actually hydrate with given ui

---

src/act-compat.js
src/index.js
tests/setup-env.js

**What**:
Enables "missing act" warnings in React 18 for test runners that implement `beforeAll` and `afterAll` (e.g. Jest).
This can be disabled the same way auto-cleanup can be disabled.
**Why**:
Ensures same behavior regarding missing act warnings across as React 16 and 17
**How**:
Set [`IS_REACT_ACT_ENVIRONMENT`](https://github.com/reactwg/react-18/discussions/102) to true once before tests start.
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) Will wait until React docs for IS_REACT_ACT_ENVIRONMENT are available.

feat: Enable "missing act" warnings in React 18 by default

---

package.json

`@types/react-dom` is used in `types/index.d.ts`, which is an external interface, and thus needs to be declared as a regular rather than a dev dependency so that it is picked up by users of `@testing-library/react`.
**What**:
This fixes #1000.
**Why**:
`@types/react-dom` is used in `types/index.d.ts`, which is an external interface, and thus needs to be declared as a regular rather than a dev dependency so that it is picked up by users of `@testing-library/react`.
**How**:
Declare `@types/react-dom` as a regular rather than a dev dependency.
**Checklist**:

fix: Add `@types/react-dom` as a direct dependency

---

src/act-compat.js

Failures are fixed with https://github.com/testing-library/react-testing-library/pull/1018
**What**:
Only use documented testing APIs
**Why**:
There's no explicit mention of "isomorphic act" landing with React 18 so let's just drop it's usage (`react-dom/test-utils` uses it anyway). Removing its usage simplifies code while also using less React internals.
**How**:
Drop usage of `React.unstable_act`
**Checklist**:
- ~[ ]~ Tests

chore: Drop usage of isomorphic act

---

.codesandbox/ci.json
package.json

Unclear why codesandbox/ci is failing. Clean clone does not fail `npm run build` on node 12 or node 14.
But forcing `npm` instead of `yarn` seems to work so 🤷🏻‍♂️

chore: Fix failing codesandbox/ci

---

.github/workflows/validate.yml
package.json

**What**:
Support stable React 18
**Why**:
React 18 stable was released yesterday
**How**:
Update peer dependencies to require `^18.0.0`
**Checklist**:
- ~[ ]~ Tests

feat: Support stable React 18 release

---

types/test.tsx

Implicit children got removed in React 18 types (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210)

test(types): Don't assume implicit children

---

package.json

**What**: fixes https://github.com/testing-library/react-testing-library/issues/1039
**Why**: Updating to react@18 (including types) is broken when using `yarn` because it picks the wrong version
**How**: Testing
**Checklist**:

fix: Specify a non-* version for @types/react-dom

---

package.json

Targets 12.x
**What**:
Ensure no unsupported dependencies are installed
**Why**:
12.x does not support React 18
**How**:
- Constrain `@types/react` dependency to < 18
- Constraint `react` and `react-dom` peer dependency to < 18
**Checklist**:

fix: Only supports React < 18

---

.github/workflows/validate.yml

Recent 12.x merge did not run GitHub actions. 
I'm not following the current pattern for release branches so I just simplified it following the [Filter pattern cheat sheet](https://docs.github.com/en/github-ae@latest/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet).
Comfirmed to work in https://github.com/eps1lon/react-testing-library/actions/runs/2150862258
dom-testing-library has the same pattern and we probably need to port that fix over there to prevent it spreading.

chore: Run release from 12.x branch

---

types/index.d.ts

**What**: Small follow up from #991 to simply export the `RenderHookResult` interface.
**Why**: This interface can be used in Typescript tests.
**How**:
**Checklist**:

fix: Export interface RenderHookResult

---

types/index.d.ts

Hi - `@testing-library/react-hooks` exported the type `RenderHookOptions`, it would be great if it could be exported here as well since it is helpful when we write wrappers around `renderHook` (e.g. I have a wrapper to enable react-router).
**What**:
Export `RenderHookOptions`
**Why**:
It's helpful when writing own extensions to `renderHook`.
**How**:
added an export ;)
**Checklist**:

feat: Export RenderHookOptions type

---

.github/workflows/validate.yml

https://github.com/nodejs/node/issues/40030 is fixed so we can run on latest Node versions again.

chore: Run with latest Node 16 again

---

package.json
src/act-compat.js

**What**:
Closes https://github.com/testing-library/react-testing-library/issues/1061
**Why**:
Test runners like `vitest` create environments where `window` does not reflect `self`. This is not an environment that exists outside of `vitest`. This was fixed in latest versions of `vitest` (see https://github.com/vitest-dev/vitest/pull/1256).
But it's good to get in anyway to support older versions as well as other test environments that aren't configured properly but run in later versions of Node or browsers.
**How**:
Use `globalThis` if available.
**Checklist**:

feat: Use `globalThis` if available

---

src/__tests__/renderHook.js
src/pure.js
types/index.d.ts

**What**:
allow passing of all render options to renderHook
this allows using options like `legacyRoot` as well
**Why**: As discussed here:
- https://github.com/testing-library/react-testing-library/issues/509#issuecomment-1223917350
**How**:
`renderHook` uses `render` under the hood, but not all `RenderOptions` were allowed to pass - only `wrapper` was forwarded. This PR passes all other options to `render` as well.
My intention was to allow `legacyRoot`, so if you want me to limit it to this option, I can also do that. I'm not sure if all options are worth forwarding or if there are some that don't make sense.
docs site would still need to be updated - is this a separate repo / PR ?
**Checklist**:

feat(renderHook): allow passing of all render options to renderHook

---

README.md

**What**:
Updating the docs to include React peer dependency requirements.
**Why**:
Trying to install newer versions of the library with older versions of React causes an installation error
**How**:
Added instructions on how to install the older version of the library when older versions of React are needed.
**Checklist**:
ref #1111

docs: acknowledge peer dependency requirements

---

.github/workflows/validate.yml

Keeping Node.js 12.x since the current release supports it. I see no reason to drop support yet.

test: Add Node.js 18.x to test matrix

---

package.json
src/__tests__/cleanup.js
src/__tests__/new-act.js
src/__tests__/render.js
src/__tests__/renderHook.js
tests/failOnUnexpectedConsoleCalls.js
tests/setup-env.js
tests/shouldIgnoreConsoleError.js
tests/toWarnDev.js

**What**:
Fail tests on `console.error` and `console.warn` calls that are not asserted (i.e. some spy intercepts them).
Also adds dedicated `toWarnDev` and `toErrorDev` matchers (see changed tests).
That help surfacing the intended errors better in tests. 
**Why**:
Otherwise we might add tests that include "missign act" warnings which this library is trying to avoid (e.g. in https://github.com/testing-library/react-testing-library/pull/1137 the added test would all "pass" without any change to the implementation).
**How**:
Copy (and adjust) the pattern facebook/react uses.
**Checklist**:

test: Fail on unexpected console.warn and console.error

---

.codesandbox/ci.json
.github/workflows/validate.yml
package.json

BREAKING CHANGE: Minimum supported Node.js version is now 14.x
**What**:
Drop support for Node.js 12.x
**Why**:
Reached EOL in April 2022. Tooling is starting to drop Node.js 12.x (see JSDOM) as well so it's time to upgrade to be able to test compat with latest test frameworks (e.g. Jest).
**How**:
Targetting alpha for now. Want to batch this with https://github.com/testing-library/dom-testing-library/issues/1202
Same as https://github.com/testing-library/dom-testing-library/pull/1207
**Checklist**:

feat: Drop support for Node.js 12.x

---

package.json
src/__tests__/end-to-end.js
src/pure.js

**What**:
Closes https://github.com/testing-library/react-testing-library/issues/1125
Closes https://github.com/testing-library/react-testing-library/issues/1051
**Why**:
Once the `callback` passed to `waitFor` resolves, there could be other microtasks scheduled.
If we now yield back from `waitFor` we restore the `REACT_IS_ACT_ENVIRONMENT`. However, the tester `await`s the `waitFor` and before the runtime yields back to the event loop, it needs (by spec) to drain the scheduled microtasks. This may include state updates which now run without `REACT_IS_ACT_ENVIRONMENT` which triggers warning.
**How**:
Drain microtask queue before resolving `waitFor` call.
**Checklist**:
- ~[ ]~ TypeScript …

fix: Prevent "missing act" warning for queued microtasks

---

.codesandbox/ci.json
.github/workflows/validate.yml
package.json
src/__tests__/cleanup.js
src/__tests__/debug.js
src/__tests__/end-to-end.js
src/__tests__/new-act.js
src/__tests__/renderHook.js
src/pure.js
tests/setup-env.js
tests/toWarnDev.js
types/test.tsx

Will be a fast-forward merge
* Prevent "missing act" warning for queued microtasks ([#1137](https://github.com/testing-library/react-testing-library/issues/1137)) ([f78839b](https://github.com/testing-library/react-testing-library/commit/f78839bf4147a777a823e33a429bcf5de9562f9e))
* Bump `@testing-library/dom` to 9.0.0 ([#1177](https://github.com/testing-library/react-testing-library/issues/1177)) ([6653c23](https://github.com/testing-library/react-testing-library/commit/6653c239c0acbafd204326c8951cde8206d39898))
* See https://github.com/testing-library/dom-testing-library/releases/tag/v9.0.0
* Drop support for Node.js 12.x ([#1169](https://github.com/testing-library/react-testing-library/issues/1169)) ([9b7a1e2](https://github.com/testing-library/react-testing-library/commit/9b7a1e2bea5bf2 …

release: 14.0.0

---

.github/workflows/validate.yml

**What**:
Following the [react announcement of canary version](https://react.dev/blog/2023/05/03/react-canaries), I believe we should test on the `canary` channel and since it's just a rename, I believe removing the `next` channel is fine.
**Why**:
**How**:
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs)~~

chore: rename `next` channel to `canary`

---

src/__tests__/end-to-end.js
src/pure.js

Tests in https://github.com/testing-library/react-testing-library/pull/1137 didn't actually show why we need it.
New tests fail without https://github.com/testing-library/react-testing-library/pull/1137 (https://github.com/testing-library/react-testing-library/actions/runs/5047921618/jobs/9055439894?pr=1215) but pass with latest code.

test: Add test for flushing before exiting `waitFor`

---

README.md

**What**: Resolves #1228
**Why**: The linked site is no longer available.
**How**:
**Checklist**:

docs(readme): remove deprecated link

---

src/index.js

**What**: Resolves #1249 
**Why**: To prevent the warning from being logged in every test suite.
**How**:
**Checklist**:

fix: log globals warning only once

---

src/index.js

**What**: This PR reverts #1252 and #1244. Resolves #1253.
**Why**: The changes here doesn't provide much added value and should be properly documented instead.
Since we can't provide a good experience for users that are manually calling `afterEach` without globals, we prefer documenting it properly.
**How**:
**Checklist**:

fix: revert missing hooks warnings

---

src/__tests__/__snapshots__/render.js.snap
src/__tests__/config.js
src/__tests__/render.js
src/__tests__/rerender.js
src/config.js
src/pure.js
types/index.d.ts
types/test.tsx

**What**:
Add `reactStrictMode` option to enable strict mode render
**Why**:
ref: https://github.com/testing-library/react-testing-library/issues/338
**How**:
This PR updates `getConfig` and `configure` functions from DTL for handling RTL options (e.g. `reactStrictMode`).
This PR also wraps UI in `render` function with `React.StrictMode` component when `reactStrictMode` is true.
By default, `reactStrictMode` is false. (according to https://github.com/testing-library/react-testing-library/issues/338)
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) -> https://github.com/testing-library/testing-library-docs/pull/1318

feat: add `reactStrictMode` option to enable strict mode render

---

types/index.d.ts
types/test.tsx

**What**: Fixes: https://github.com/testing-library/react-testing-library/issues/1271
**Why**: To improve typescript types
**How**: N/A
**Checklist**:

fix: Update types to support all possible react component return values

---

.github/workflows/validate.yml
jest.config.js
package.json
src/__tests__/render.js
src/__tests__/renderHook.js
tests/toWarnDev.js

Fixing 
```
[test] FAIL src/__tests__/render.js (9.164 s)
[test]   ● render API › legacyRoot uses legacy ReactDOM.render
[test] 
[test]     TypeError: jestDiff is not a function
[test] 
[test]       161 |           errorMessage =
[test]       162 |             'Unexpected warning recorded: ' +
[test]     > 163 |             jestDiff(expectedMessages[0], normalizedMessage)
[test]           |             ^
[test]       164 |         } else {
[test]       165 |           errorMessage =
[test]       166 |             'Unexpected warning recorded: ' +
[test] 
[test]       at console.jestDiff (tests/toWarnDev.js:163:13)
[test]       at printWarning (node_modules/react-dom/cjs/react-dom.development.js:105:30)
[test]       at error (node_modules/react-dom/cjs/react-dom.development.js:79:7)
[test] …
```

chore: Fix tests

---

types/index.d.ts

Removing this now since that'll also ensure forwards compatibility with React 19 from a types perspective.

fix: Remove unused types

---

.github/workflows/validate.yml
codecov.yml

Followed https://github.com/codecov/codecov-action#usage
Updated other actions as a drive-by (though checkout should probably also be latest for maximum interop with codecov action)
codecov/codecov-action docs: https://github.com/codecov/codecov-action#usage

chore: Update Codecov configuration to latest

---

src/__tests__/render.js

Following this comment in @eps1lon's PR: https://github.com/testing-library/react-testing-library/pull/1288#discussion_r1531897751

chore: change canary version to specific prefix

---

.github/workflows/validate.yml
jest.config.js
src/__tests__/new-act.js
src/__tests__/render.js
src/__tests__/renderHook.js
src/act-compat.js
src/pure.js
types/index.d.ts

Closes https://github.com/testing-library/react-testing-library/pull/1270
We can release React 19 support as a SemVer MINOR. Even though `legacyRoot` is no longer supported, it's not really a RTL breaking change but a React breaking change that's handled in their SemVer MAJOR release. It would only be a RTL breaking change if React would be a direct dependency not a peer dependency as it is now.

feat: Add support for React 19 Canary

---

.codesandbox/ci.json
.github/workflows/validate.yml
package.json

BREAKING CHANGE: Minimum supported Node.js version is 18.0
BREAKING CHANGE: New version of `@testing-library/dom` changes various roles. Check out the changed tests in https://github.com/testing-library/dom-testing-library/commit/2c570553d8f31b008451398152a9bd30bce362b3 to get an overview about what changed.
More details about this change can be found in the [DTL release](https://github.com/testing-library/dom-testing-library/releases/tag/v10.0.0).

Release: 15.0.0

---

src/act-compat.js

It's not supported by some older bundlers and we don't need to use the syntax to begin with (really). Will backport to 14.x since the latest 14.x was only out for 2 days.

fix: Stop using nullish coalescing

---

src/__tests__/render.js
src/__tests__/renderHook.js
src/pure.js

Applies suggestions by @wojtekmaj from https://github.com/testing-library/react-testing-library/pull/1294#discussion_r1557073011

fix: Improve `legacyRoot` error message

---

types/index.d.ts
types/test.tsx

Closes https://github.com/testing-library/react-testing-library/issues/1250
As a follow-up, we need to make `@types/react-dom` a peer dependency. Since `react-dom` is a peer, the types also need to be peer. Otherwise you would get the wrong version of `@types/react-dom` if you'd install React 19.

fix: Don't raise TypeScript errors when hydating `document`

---

types/index.d.ts
types/test.tsx

Fixes https://github.com/testing-library/react-testing-library/issues/1307

fix: Ensure `renderHook` options extend options for `render`

---

types/index.d.ts
types/test.tsx
types/tsconfig.json

Closes https://github.com/testing-library/react-testing-library/issues/1312
Closes https://github.com/testing-library/react-testing-library/issues/1311
It's really not worth it to have such extensive types just to restrict `container` properly. Especially because it makes composing `render` and `renderHook` so hard. And we do want to encourage wrapping `render` in your tests.

fix: Stop restricting `container` option based on `hydrate`

---

package.json
src/__tests__/stopwatch.js
tests/shouldIgnoreConsoleError.js

Work around https://github.com/facebook/react/issues/28915. Should be fixed in 18.3.0 but the special casing should remain in case we need to test against 18.3.0 specifically.

chore: Adjust tests to workaround 18.3.0 bug

---

package.json
types/index.d.ts

Resolves https://github.com/testing-library/react-testing-library/issues/1316
**What**: This PR exports the correct act if available to avoid deprecation warnings.

fix: export new act when available

---

types/index.d.ts

Tested in https://github.com/eps1lon/rtl-deprecated-act-repro/commit/af593bdcf9296ded91df39ba803cfc09b67fd691
Required for https://github.com/vercel/front/pull/32113

fix: Ensure `act` is not `any` when `React.act` is not declared

---

README.md
package.json

Closes https://github.com/testing-library/react-testing-library/issues/1184
Docs: https://github.com/testing-library/testing-library-docs/pull/1384
**BREAKING CHANGE**:
`@testing-library/dom` was moved to a peer dependency and needs to be explicitly installed. This reduces the chance of having conflicting versions of `@testing-library/dom` installed that frequently caused bugs when used with `@testing-library/user-event`. We will also be able to allow new versions of `@testing-library/dom` being used withou a SemVer major release of `@testing-library/react` by just widening the peer dependency.
`@types/react-dom` needs to be installed if you're typechecking files using `@testing-library/react`.
Type dependencies need to match their runtime counterpart.
If `foo` is a dependency, …

feat: Move `@testing-library/dom` and `@types/react-dom`  to peer dependencies

---

types/index.d.ts
types/test.tsx
types/tsconfig.json

Closes https://github.com/testing-library/react-testing-library/issues/1320
Just going through each `?` that indicates an optional property and ensuring `undefined` is accepted. We don't differentiate the two at runtime.

fix: Add support for exactOptionalPropertyTypes in TypeScript

---

package.json
types/test.tsx

Just relaxing peer dependencies and adjusting for `@types/react@19` in a backwards compatible manner.
Closes https://github.com/testing-library/react-testing-library/issues/1364

feat: Add support for React 19

---

package.json
src/__tests__/error-handlers.js
src/pure.js
tests/toWarnDev.js
types/index.d.ts
types/test.tsx

**What**:
Alternate to https://github.com/testing-library/react-testing-library/pull/1333
Adds support for `onRecoverableError` and `onCaughtError` (React 19 only)
`onUncaughtError` is not supported yet because there's no use. The `render` would throw anyway. We're likely going to change that though in React.
**Why**:
This allows test setups that fail on console errors to silence specific, expected errors in their tests.
Especially `onCaughtError` will simplify testing of error boundaries since it will disable React's default console.error + window.onError dispatch (see docs I'll add soon)
**How**:
Forward mentioned options to React's `createRoot` call.
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs): …

feat: Add support for React error handlers

---

package.json

i.e. update `devDependencies` to use 19.
18 is still tested in CI.

test: Use React 19 by default

---

.github/workflows/validate.yml

This has no effect right now since `latest` and `18.x` point at the same version.
Once React 19 is out, we'll be running tests in both 18 and 19.
The types should match that dimension.
Ideally, we'd be able to test RC types but npm claims `npm install @types/react@npm:types-react@rc` is an invalid comparator.
Putting that in the package.json works but I'm too lazy to write a dedicated script right now.

test: Run with relevant React stable types

---

src/__tests__/render.js
src/__tests__/renderHook.js
src/pure.js
types/index.d.ts

**What**:
Add an ability to override the global `reactStrictMode` configuration on a per-test basis. 
**Why**:
At MUI, our tests use a small wrapper around React Testing Library and [had this functionality](https://github.com/mui/material-ui/blob/a80e7b7270a1af786870b7a4ad84a1d17c4ce5bd/packages-internal/test-utils/src/createRenderer.tsx#L639). However, it was broken in the upgrade to React 19 since `StrictMode` won't double call effects on initial mount unless `StrictMode` is rendered at the root of the tree. Since we were rendering `React.StrictMode` inside the component passed to the `wrapper` property, effects aren't being called twice in React 19. 
**How**:
Added a `reactStrictMode` to `renderOptions`. 
**Checklist**:

Add `reactStrictMode` as an option to `render`

---

package.json

[`npm-run-all`](https://npm.im/npm-run-all) is unmaintained and an active & up-to-date fork is now available as [`npm-run-all2`](https://npm.im/npm-run-all2)
---
I'm sure people from the wider @e18e ecosystem cleanup (like @43081j, @benmccann, @Fuzzyma, @outslept & @talentlessguy) will be very happy to see these kind of changes as well

chore(deps): use `npm-run-all2`
