.all-contributorsrc
README.md
src/index.js

**What**: Rename the internal utility `sel` to `select`
**Why**: Better readability.
**How**: N/A
**Checklist**:

rename internal utility sel to select

---

package.json

**What**: Added missing folder.
**Why**: `typings` folder was not exposed to dist directory
**How**: With my hands 😄 
**Checklist**:
Sorry to bother you again but forgot to do it. I was doing it first time 😭

fix(definitions): add missing 'typings' folder to files property

---

README.md

**What**:
**Why**:
**How**:
**Checklist**:

Fix you->your typo

---

package.json

**What**: A simple miss
**Why**: A simple bug :)
**How**: Added the necessary fix. 
**Checklist**:

Adding the missed file `"extend-expect.js"`

---

src/__tests__/element-queries.js
src/jest-extensions.js

**What**: Jest `message` should be a function, we have returned a string, so in case of failure, the API is breaking. 
**Why**:
**How**: Moved them to functions and wrote coverage test cases for them as well. 
**Checklist**:

Message should be function and added test cases for the coverage as well

---

.github/ISSUE_TEMPLATE/Feature_Request.md

**What**:
Part of the text was more appropriate for bug reports, and this commit adapts that to feature requests instead.
**Checklist**:

Update Feature Request issue template

---

README.md

**What**:
Added link to "Integration testing in React" to "Learning Material" section of README, which compares react-testing-library to Enzyme.
**Why**:
To help illustrate the differences between react-testing-library and Enzyme.
**Checklist**:

Add "Integration testing in React" to README

---

README.md

tiny wording fix

---

README.md

**What**:
Small PR to add the blog post article [Creating Readable Tests Using React Testing Library](https://medium.com/flatiron-labs/creating-readable-tests-using-react-testing-library-2bd03c49c284) to the [Learning Material](https://github.com/kentcdodds/react-testing-library#learning-material) section.
**Why**:
To add additional resources to Learning Material
**Checklist**:

Add additional learning material to README

---

.all-contributorsrc
README.md

**What**:
**Why**:
**How**:
**Checklist**:
- [x ] Documentation
- [ x] Tests
- [x ] Ready to be merged
- [x ] Added myself to contributors table
Thank you. Have a great day.

adding myself as contributor

---

README.md

**What**:
I've added the react-testing-library course repository from Kent C. Dodds inside the Learning Materials section.
**Why**:
This repo contains many examples that can help everyone that is using this fantastic library.
**How**:
N / A
**Checklist**:

Added new topic inside Learning Materials

---

.github/ISSUE_TEMPLATE/Bug_Report.md

**What**:
Minor grammar fix in comment in bug report issue template.
**Checklist**:

Grammar correction in bug report issue template

---

README.md

**What**:
Mention [`react-native-testing-library`](https://github.com/callstack/react-native-testing-library) as a React Native solution for this lib.
**Why**:
Since it's a sibling project, I think it's worth to mention it here :)
**How**:
**Checklist**:
cc @kentcdodds

docs: mention react-native-testing-library

---

README.md

**What**:
Found some typos on strings #565 and #1106
**Why**:
For better and proper clarity of the documentation. This project deserve the best (_imho_).
**How**:
This pull request is based only in the `readme.md` file
**Checklist**:
- [x ] Documentation
- [ x] Tests
- [ x] Ready to be merged
- [x ] Added myself to contributors table

Typos on string #565 & #1106

---

README.md

Not sure you'll find this useful. But I think the additional examples might help people getting started with RTL.

Link to external examples

---

typings/index.d.ts

**What**: I've added typings for `flushEffects` function.
**Why**: I know it's an experimental feature and you're looking for a better solution, but as long as this function is actually exported it will be good to have typings for it.
**How**: I've taken the comment for the function directly from README.
**Checklist**:

flushEffects() typings

---

package.json

Update dom-testing-library dependency

---

README.md

🤷‍♂️ 
**What**:
**Why**:
**How**:
**Checklist**:

chore: center the docs links

---

.github/PULL_REQUEST_TEMPLATE.md

**What**:
**Why**:
**How**:
**Checklist**:

Add TS to PR checklist

---

.github/PULL_REQUEST_TEMPLATE.md

**What**:
Response to feedback that doc repo is hard to find
**Why**:
**How**:
**Checklist**:

Docs: add link to docs repo in PR template

---

src/act-compat.js

**What**: add try/catch around react-dom/test-utils require
**Why**: Closes #315
**How**: replace import with require so we can make it happen dynamically
**Checklist**:

fix(act): add try/catch around react-dom/test-utils require

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/Bug_Report.md
.github/ISSUE_TEMPLATE/Question.md

**What**:
Because people keep filing bug reports for the docs here 😅 
**Why**:
**How**:
**Checklist**:

docs: link issue templates to docs repo

---

README.md

Added a dot to end of section about Hooks.
**What**:
**Why**:
**How**:
**Checklist**:

Added a dot to end of section about Hooks

---

typings/index.d.ts

**What**: Export `Queries` interface to make it easier to define a custom `render`, e.g.
```js
import { render } from '@my-design-system/test-utils'
// Pass in a custom theme which the custom `render` wires up to a `ThemeProvider`
render(<MyDesignSystemButton />, { theme: { someColor: 'blue' } })
```
**Why**: Closes #395.
**How**: Export `Queries` interface which is referenced by `render` in `index.d.ts`.
**Checklist**:

fix(TS): export `Queries` interface

---

README.md

**What**:
There are some typos in Complex Example code.
**Why**:
Example code should be correct.
**How**:
Change the method name and variable name.
**Checklist**:
[docs site](https://github.com/testing-library/react-testing-library#complex-example)

docs: Add missing characters in complex example

---

.travis.yml

**What**:
Tests library across node versions
**Why**:
To ensure library works on all Node LTS releases
**How**:
Adding a build matrix to travis ci.
**Checklist**:

ci: test with node 8, 10, and 12

---

README.md

made license text point to the respective file

Docs: update license info

---

.travis.yml
package.json

**What**: support older Node 10 versions
**Why**: to make the upgrade easier since there doesn't appear to be a hard requirement to use Node 10.18 (see https://github.com/testing-library/dom-testing-library/pull/459#issuecomment-595565564).
**How**: changed `engines.node` from `>=10.18` to `>=10` and updated Travis to use Node.js 10.0.0.
**Checklist**:

fix: support Node >=10

---

package.json

**What**: update `@testing-library/dom`
**Why**: Closes https://github.com/testing-library/user-event/issues/304
**How**: GitHub edit on `package.json`
**Checklist**:

fix: force update version of @testing-library/dom

---

package.json
pure.d.ts

fix(TS): add type defs file for pure

---

README.md

**What**: Fix the documentation in the README.md file to separate the basic example code block
**Why**: OCD/keep with uniformity with how the other example code blocks are structured
**How**: 
**Checklist**:

fix(docs): separate basic example code block

---

package.json

**What**: I removed @reach/router from our devDependencies.
**Why**: I saw that it's not being used in the project.
**How**:
**Checklist**:
[docs site](https://github.com/testing-library/testing-library-docs) - N/A

chore(package): remove reach/router from devDependencies since it's not in use

---

package.json

**What**:
Bump @testing-library/dom to v7.26.0
**Why**:
to use the `logPlaygroundUrl` method added to the `screen` 
**How**:
**Checklist**:

fix: Bump @testing-library/dom to v7.26.0

---

types/test.tsx

**What**:
I fixed type parameter of queries test.
**Why**:
I made a trivial mistake in #871.
**How**:
**Checklist**:

chore(types): fix type parameter of Queries test

---

src/__tests__/events.js

**What**:
Fixes typo in test name. 
**Why**:
Grammar.
**How**:
`blur/foucs` -> `blur/focus`
**Checklist**:

test: fix typo

---

CONTRIBUTING.md

**What**: The fix of a link to an external site explaining the contribution process
**Why**: to polish the developer experience
**How**: modified the link to the correct one
**Checklist**:

docs: Fix link to egghead open source contribution how to

---

.github/workflows/validate.yml

**What**:
Don't test with node 15
**Why**:
Node 15 reached EOL on June, 1st so let's free up some CI ressources.
**How**:
Remove 15 from node test matrix.
**Checklist**:

chore: Don't test with node 15

---

.github/workflows/validate.yml

Cherry-picking https://github.com/testing-library/react-testing-library/pull/1044

chore: Ensure support for releases from release branches 

---

.github/workflows/validate.yml

Same as https://github.com/testing-library/dom-testing-library/pull/1214

chore: Allow semantic-release to post updates in issues

---

package.json

https://github.com/testing-library/dom-testing-library/releases/tag/v9.0.0
Minimum Node.js version matches already.
`ByRole` changes are just passed along.

feat: Bump `@testing-library/dom` to 9.0.0  

---

src/act-compat.js

Cherry-picks https://github.com/testing-library/react-testing-library/pull/1299 into 14.x
Closes https://github.com/testing-library/react-testing-library/issues/1298

fix: Stop using nullish coalescing

---

.github/workflows/validate.yml

Fixes https://github.com/testing-library/react-testing-library/actions/runs/12798352706/job/35682204149?pr=1354: https://app.codecov.io/github/testing-library/react-testing-library/commit/27bcafab5eec75921752102e7e9796555b628251

[ci] Fix codecov action
